version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asciicheck
    - durationcheck
    - copyloopvar
    - contextcheck
    - errcheck
    - errchkjson
    - errname
    - fatcontext
    # - gocritic
    # - goconst
    - gocyclo
    - godox
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - intrange
    - mirror
    - musttag
    - nilerr
    # - predeclared not sure
    - revive
    - sloglint
    - staticcheck
    - tagliatelle
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
